# Number of devotion points available
points = 47

# Weapon types you will be using.  A star's bonuses only count if you meet the weapon requirement.
# Possible weapons types are: Dagger, Axe, Axe2h, Mace, Mace2h, Offhand, Ranged1h, Ranged2h, Shield,
# Spear, Staff, Sword, Sword2h.  See './info.py w' for descriptions.
weapons = ['Offhand', 'Staff']

# Which celestial powers to unlock (case insensitive). Run './info.py p' for a full list
celestial_powers = ["raise the dead"]
#celestial_powers = ["raise the dead", "elemental seeker"]
# celestial_powers = ["elemental seeker"]

# Force these stars to be picked. Format is '[Constellation] [Index]', case insensitive; for example
# 'Revenant 0' or 'Vire the Stone Matron 5'.
stars = []


[[bonus]]
# X-Y Aether Damage
# value = 0.5 * (X + Y)
kind = "Damage.Aether"
weight = 1

[[bonus]]
# X-Y Cold Damage
# value = 0.5 * (X + Y)
kind = "Damage.Cold"
weight = 1


[[bonus]]
# X% Aether Damage
# value = X
kind = "DamageModifier.Aether"
weight = 20

[[bonus]]
# X% Cold Damage
# value = X
kind = "DamageModifier.Cold"
weight = 3

[[bonus]]
# X% Cold Damage
# value = X
kind = "DamageModifier.Fire"
weight = 1

[[bonus]]
# X% Frostburn Damage with Y% Increased Duration
# value = X + Y
kind = "DamageOverTimeModifier.Cold"
weight = 5

[[bonus]]
# X% Reduced target's Elemental Resistances for Y Seconds
# value = X * Y
kind = "ResistanceReduction.Elemental"
weight = 5

[[bonus]]
# X% Energy Absorbed from Enemy Spells
# value = X
kind = "characterEnergyAbsorptionPercent"
weight = 10

[[bonus]]
# X Spirit
# value = X
kind = "characterIntelligence"
weight = 1

[[bonus]]
# X% Spirit
# value = X
kind = "characterIntelligenceModifier"
weight = 20


[[bonus]]
# X Health Regenerated per second
# value = X
kind = "characterLifeRegen"
weight = 5

[[bonus]]
# Increases Health Regeneration by X%
# value = X
kind = "characterLifeRegenModifier"
weight = 5

[[bonus]]
# X% Energy
# value = X
kind = "characterManaModifier"
weight = 25

[[bonus]]
# X Energy Regenerated per second
# value = X
kind = "characterManaRegen"
weight = 200

[[bonus]]
# Increases Energy Regeneration by X%
# value = X
kind = "characterManaRegenModifier"
weight = 40


[[bonus]]
# X-Y% of Attack Damage converted to Health
# 0.5 * (X + Y)
kind = "Damage.LifeLeech"
weight = 10

[[bonus]]
# -X% Skill Energy Cost
# value = X
kind = "skillManaCostReduction"
weight = 200
